#!/usr/bin/env python

# ch5/ex36
import random
from sys import argv

from solutions.exercises.ch5.ex35.substitution_cipher import SubstitutionCipher


class CaesarCipher(SubstitutionCipher):
    def __init__(self, shift):
        super().__init__(''.join([chr((k + shift) % 26 + ord('A')) for k in range(26)]))


def _main():
    shift = 3 if len(argv) < 2 else int(argv[1])
    original_msg = "HELLO WORLD!" if len(argv) < 3 else argv[2]
    cc = CaesarCipher(shift)
    print("Original Message: {}".format(original_msg))
    encrypted_msg = cc.encrypt(original_msg)
    print("Encrypted Message: {}".format(encrypted_msg))
    print("Decrypted Message: {}".format(cc.decrypt(encrypted_msg)))


if __name__ == "__main__":
    _main()