#!/usr/bin/env python

# ch2_ex11

from solutions.vendor.ch02.vector import Vector as Ch2Vector
from solutions.libs.utils.argv import parse_int_list


class Vector(Ch2Vector):
    def __radd__(self, other):
        """Return sum of two vectors."""
        if len(self) != len(other):  # relies on len method
            raise ValueError('dimensions must agree')
        result = Vector(len(self))  # start with vector of zeros
        for j in range(len(self)):
            result[j] = self[j] + other[j]
        return result


if __name__ == "__main__":
    seq_a = [5, 3, 10, -2, 1]
    seq_v = parse_int_list(1)[0]

    vector_v = Vector(len(seq_v))
    for i in range(len(vector_v)):
        vector_v[i] = seq_v[i]

    print(seq_a + vector_v)
