#!/usr/bin/env python3

# ch1/ex14

from solutions.libs.utils.argv import parse_int_list


def odd_product_pair(seq):
    pair = []
    for n in seq:
        if n & 1 == 1:
            pair.append(n)
            if len(pair) == 2:
                break;
    return len(pair) == 2, pair


def has_odd_product_pair(seq):
    return odd_product_pair(seq)[0]


if __name__ == "__main__":
    seq = parse_int_list(1)[0]
    result = odd_product_pair(seq)
    print("%s %s a pair whose product is odd." % (seq, "has" if result[0] else "does not have"))
    if result[0]:
        print("%i x %i = %i" % (result[1][0], result[1][1], result[1][0] * result[1][1]))
