#!/usr/bin/env python3

# ch6/ex3
from sys import argv

from solutions.exercises.ch6.ex3.transfer import transfer
from solutions.vendor.ch06.array_stack import ArrayStack as Ch6ArrayStack


def _main():
    S = Ch6ArrayStack()
    T = Ch6ArrayStack()

    for i in range(int(argv[1]) if len(argv) > 1 else 10):
        S.push(i)
    print("S: {}".format(S))
    print("T: {}".format(T))
    print("Transferring from S to T ...")
    transfer(S, T)
    print("S: {}".format(S))
    print("T: {}".format(T))


if __name__ == "__main__":
    _main()
