#!/usr/bin/env python

# ch6/ex36
from math import floor
from sys import argv
from os import path as os_path

from solutions.exercises.ch6.ex36.gain_tracker import GainTracker


def _main():
    path: str = argv[1] if len(argv) > 1 else os_path.join(os_path.dirname(os_path.realpath(__file__)), "trades.txt")
    file = open(path, "r")
    line: str
    gain_tracker = GainTracker()
    for line in file:
        line = line.strip()
        if len(line) > 1:
            fields: list[str] = line.split()
            shares: int = int(fields[1])
            price_in_cents: int = floor(float(fields[4].lstrip("$")) * 100)
            if fields[0] == "buy":
                gain_tracker.buy(shares, price_in_cents)
            elif fields[0] == "sell":
                gain_tracker.sell(shares, price_in_cents)
            else:
                raise ValueError("Invalid transaction type: {}".format(fields[0]))
    print("total capital gain: ${:.2f}".format(gain_tracker.get_gains_in_cents() / 100))


if __name__ == "__main__":
    _main()
