#!/usr/bin/env python

# ch6/ex15
import random
from sys import argv

from solutions.vendor.ch06.array_stack import ArrayStack


def guess_max(s: ArrayStack):
    x = s.pop()
    if x < s.top():
        x = s.top()
    s.push(x)
    return x


def _main():
    trials = int(argv[1]) if len(argv) > 1 else 1000000
    correct_guesses = 0
    for _ in range(trials):
        _max = float("-inf")
        seen = set()
        s = ArrayStack()
        while len(seen) < 3:
            curr = random.randrange(1024)
            if curr not in seen:
                s.push(curr)
                _max = max(_max, curr)
                seen.add(curr)
        if guess_max(s) == _max:
            correct_guesses += 1
    print("Guessed the maximum correctly in {} out of {} trials ({:.4f}%)!".format(correct_guesses, trials,
                                                                                   100.0 * correct_guesses / trials))


if __name__ == "__main__":
    _main()
