#!/usr/bin/env python

# ch6_ex17
from sys import argv

from solutions.exercises.ch6.ex16.full import Full
from solutions.exercises.ch6.ex28.max_len_array_queue import MaxLenArrayQueue


def _main():
    maxlen = int(argv[1]) if len(argv) > 1 else 10
    s = MaxLenArrayQueue(maxlen)
    print("s has a maxlen of {}.".format(maxlen))
    for i in range(maxlen):
        s.enqueue(i)
    print("s: {}".format(s))
    try:
        s.enqueue(11)
    except Full as e:
        print("The following error was raised while enqueueing onto s:")
        print(e)
    print("s: {}".format(s))
    t = MaxLenArrayQueue()
    print("t has a maxlen of None.")
    for i in range(maxlen):
        t.enqueue(i)
    print("t: {}".format(t))
    for i in range(maxlen, 2 * maxlen):
        t.enqueue(i)
    print("t: {}".format(t))
    print("We can enqueue as many elements as we want onto t!")


if __name__ == "__main__":
    _main()
