#!/usr/bin/env python

from os import path as os_path
from sys import argv
from sys import path as sys_path

sys_path.insert(0, os_path.join(os_path.dirname(__file__), "aliases"))

from aliases.util import get_alias_list

print(get_alias_list(argv[1] if len(argv) > 1 else ""))
