#!/usr/bin/env bash

cmd="export PYTHONPATH=\"\$PYTHONPATH:$PWD\""

if [ -f ~/.bash_profile ];  then
    shell_config_file_path=~/.bash_profile
elif [ -f ~/bashrc ]; then
    shell_config_file_path=~/.bashrc
else
    echo "Cannot find shell config file"
    exit 2;
fi

if grep "$cmd" "$shell_config_file_path" > /dev/null 2>&1; then
    echo "Already loaded"
else
    echo "# Convenience for running solutions to exercises in Data Structures and Algorithms in Python" \
        >> "$shell_config_file_path"
    echo "$cmd" >> "$shell_config_file_path"
fi