#!/usr/bin/env python

from sys import argv
from sys import exit
from sys import path as sys_path
from os import path as os_path
from subprocess import Popen

sys_path.insert(0, os_path.join(os_path.dirname(__file__), "aliases"))

from aliases.util import get_alias_path

command = ['pipenv', 'run', 'python']

command.append(get_alias_path(argv[1]))
command.extend(argv[2:])

exit(Popen(command).wait())
