#!/usr/bin/env python

# ch6/ex33
from sys import argv

from solutions.exercises.ch6.ex33.collections_deque import CollectionsDeque


def _main():
    n = int(argv[1]) if len(argv) > 1 else 20
    deque = CollectionsDeque()
    for i in range(0, n, 2):
        if not deque.is_empty():
            print("first: {}".format(deque[0]))
            print("last: {}".format(deque[-1]))
        print("deque: {}".format(deque))
        print("add_first {} onto deque ...".format(i))
        deque.appendleft(i)
        print("add_last {} onto deque ...".format(i + 1))
        deque.append(i + 1)
    while not deque.is_empty():
        print("first: {}".format(deque[0]))
        print("last: {}".format(deque[-1]))
        print("deque: {}".format(deque))
        print("delete_first {} off of queue.".format(deque.popleft()))
        print("delete_last {} off of queue.".format(deque.pop()))
    print(deque)


if __name__ == "__main__":
    _main()
