#!/usr/bin/env python

# ch5/ex32
from typing import Sequence

from solutions.libs.utils.argv import parse_int_matrix


def sum_matrices(A, B):
    L = len(A)
    M = len(A[0])
    N = len(A[0][0])

    if len(B) != L or len(B[0]) != M or len(B[0][0]) != N:
        raise ValueError("A and B must have the same dimensions!")

    result = [[[0 for _ in range(N)] for _ in range(M)] for _ in range(L)]

    for i in range(L):
        for j in range(M):
            for k in range(N):
                result[i][j][k] = A[i][j][k] + B[i][j][k]

    return result


if __name__ == "__main__":
    A, current_index = parse_int_matrix(1)
    B = parse_int_matrix(current_index)[0]

    print(sum_matrices(A, B))
