#!/usr/bin/env python

# ch1_ex3

from solutions.libs.utils.argv import parse_int_list


def minmax(seq):
    min = seq[0]
    max = seq[0]

    for i in seq:
        if i < min:
            min = i
        elif i > max:
            max = i
    return min, max


if __name__ == "__main__":
    seq = parse_int_list(1)[0]
    min, max = minmax(seq)
    print("min: %i\nmax: %i" % (min, max))
