#!/usr/bin/env python

# ch4_ex12_sc1

from sys import argv

def product(m, n):
    return _product(max(m, n), min(m, n))

def _product(m, n):
    if n == 0:
        return 0
    elif n == 1:
        return m
    else:
        return m + _product(m, n - 1)

if __name__ == "__main__":
    print(product(int(argv[1]), int(argv[2])))
