#!/usr/bin/env python3

import sys, re

def minmax(seq):
    min = seq[0]
    max = seq[0]

    for i in seq:
        if i < min:
            min = i
        elif i > max:
            max = i
    return min, max

if __name__ == "__main__":
    seq = []
    for arg in sys.argv[1:]:
        clean_arg = re.sub("[\[\](){};,]", " ", arg)
        for token in clean_arg.split(" "):
            if token not in [" ", ""]:
                seq.append(int(token))
    min, max = minmax(seq)
    print("min: %i\nmax: %i" %(min, max))
