#!/usr/bin/env python

# ch2/ex9

from solutions.vendor.ch02.vector import Vector as Ch2Vector
from solutions.libs.utils.argv import parse_int_list


class Vector(Ch2Vector):
    def __sub__(self, other):
        if len(self) != len(other):
            raise ValueError('dimensions must agree')
        result = Vector(len(self))
        for i in range(len(self)):
            result[i] = self[i] - other[i]
        return result


if __name__ == "__main__":
    current_index = 1
    seq_a, current_index = parse_int_list(current_index)
    seq_b = parse_int_list(current_index)[0]

    vector_a = Vector(len(seq_a))
    for i in range(len(vector_a)):
        vector_a[i] = seq_a[i]

    vector_b = Vector(len(seq_b))
    for i in range(len(vector_b)):
        vector_b[i] = seq_b[i]

    print(vector_a - vector_b)
