#!/usr/bin/env python3

# ch4/ex8

from solutions.libs.utils.argv import parse_int_list


def binary_sum(A):
    if len(A) == 0:
        return 0
    elif len(A) == 1:
        return A[0]
    else:
        B = []
        for i in range(0, len(A), 2):
            B.append(A[i] + A[i + 1])
        return binary_sum(B)


if __name__ == "__main__":
    print(binary_sum(parse_int_list(1)[0]))
