#!/usr/bin/env python

# ch6/ex4
from sys import argv

from solutions.vendor.ch06.array_stack import ArrayStack


def remove_all(s: ArrayStack):
    if s.is_empty():
        return
    else:
        s.pop()
        remove_all(s)


def _main():
    s = ArrayStack()
    for i in range(int(argv[1]) if len(argv) > 1 else 10):
        s.push(i)
    print("s: {}".format(s))
    print("Removing all elements from s ...")
    remove_all(s)
    print("s: {}".format(s))


if __name__ == "__main__":
    _main()
