#!/usr/bin/env python

# ch2_ex5

from sys import argv
from solutions.fragments.ch2.CreditCard import CreditCard as Ch2CreditCard
from numbers import Real


class CreditCard(Ch2CreditCard):
    def charge(self, price):
        if not isinstance(price, Real):
            raise TypeError('Price must be a real number!')
        else:
            return super().charge(price)

    def make_payment(self, amount):
        if not isinstance(amount, Real):
            raise TypeError('Amount must be a real number!')
        else:
            return super().make_payment(amount)


if __name__ == "__main__":
    price, amount = argv[1], argv[2]

    credit_card = CreditCard('Wilbur Smith', 'A Bank', '12345 67890', 5000.0)

    try:
        credit_card.charge(price)
    except TypeError as e:
        print(e)

    try:
        credit_card.make_payment(amount)
    except TypeError as e:
        print(e)

    print("Don't forget to cast your arguments as real numbers (int, float, etc.)!")

    credit_card.charge(float(price))
    credit_card.make_payment(float(amount))

    print("Balance: %.2f" % credit_card.get_balance())
    print("Remaining limit: %.2f" % (credit_card.get_limit() - credit_card.get_balance()))
