#!/usr/bin/env python

# ch5_ex16

from solutions.vendor.ch05.dynamic_array import DynamicArray as Ch5DynamicArray


class DynamicArray(Ch5DynamicArray):

    def pop(self):
        """Remove object from the end of array"""
        self._n -= 1
        tmp = self._A[self._n]
        self._A[self._n] = None
        if self._n < self._capacity / 4:
            self._resize(self._capacity // 2)
        return tmp

    def empty(self):
        return self._n < 1

    def _resize(self, c):
        print("Resizing to capacity: {}".format(c))
        super()._resize(c)


def _main():
    a = DynamicArray()
    for i in range(16):
        print("about to append: {}".format(i))
        a.append(i)
    while not a.empty():
        print("about to pop!")
        print(a.pop())


if __name__ == "__main__":
    _main()
