#!/usr/bin/env python

# ch6_ex29
from sys import argv

from solutions.exercises.ch6.ex29.rotatable_array_queue import RotatableArrayQueue


def _main():
    n = int(argv[1]) if len(argv) > 1 else 10
    Q = RotatableArrayQueue()
    for i in range(n):
        Q.enqueue(i)
    print("Q: {}".format(Q))
    for _ in range(n):
        print("Rotating Q ...")
        Q.rotate()
        print("Q: {}".format(Q))


if __name__ == "__main__":
    _main()
