#!/usr/bin/env python3

# ch1_ex29_sc1

from sys import argv

def permute_str(string):
    if len(string) == 0:
        return []
    elif len(string) == 1:
        return [string]
    else:
        permutations = []
        head = string[0]
        tail_permutations = permute_str(string[1:len(string)])
        for tail_permutation in tail_permutations:
            for i in range(0, len(tail_permutation) + 1):
                permutations.append(tail_permutation[:i] + head + tail_permutation[i:])
        return permutations


if __name__ == "__main__":
    string = "catdog" if len(argv) < 2 else argv[1]
    permutations = permute_str(string)
    for permutation in permutations:
        print(permutation)
    print("\nNumber of permutations: %i" %len(permutations))
