#!/usr/bin/env python3

import sys, re

def equivalent_index(k, seq):
    n = len(seq)
    return k + n if k < 0 else k - n

if __name__ == "__main__":
    k = int(sys.argv[1])
    seq = []
    for arg in sys.argv[2:]:
        clean_arg = re.sub("[\[\](){};,]", " ", arg)
        for token in clean_arg.split(" "):
            if token not in [" ", ""]:
                seq.append(int(token))
    l = equivalent_index(k, seq)
    print("seq[%i] is %sequal to seq[%i]" %(k, "" if seq[k] == seq[l] else "not", l))
