#!/usr/bin/env python3

# ch1_ex8_1

import sys, re
from exercises.argv_utils import parse_int_seq

def equivalent_index(k, seq):
    n = len(seq)
    return k + n if k < 0 else k - n

if __name__ == "__main__":
    k = int(sys.argv[1])
    seq = parse_int_seq(2)[0]
    l = equivalent_index(k, seq)
    print("seq[%i] is %sequal to seq[%i]" %(k, "" if seq[k] == seq[l] else "not", l))
