#!/usr/bin/env python

# ch1_ex30_sc2

from sys import argv

def divide_by_two(n):
    return divide_by_two(n/2) + 1 if n >= 2 else 0

if __name__ == "__main__":
    print(divide_by_two(int(argv[1])))
