#!/usr/bin/env python

# ch2_ex18

from sys import argv
from solutions.fragments.ch2.FibonacciProgression import FibonacciProgression

if __name__ == "__main__":
    n = int(argv[1]) if len(argv) > 1 else 8
    progression = FibonacciProgression(2, 2)

    for _ in range(n-1):
        next(progression)

    print(next(progression))
