#!/usr/bin/env python3

# ch2/ex18

from sys import argv

from solutions.vendor.ch02.progressions import FibonacciProgression

if __name__ == "__main__":
    n = int(argv[1]) if len(argv) > 1 else 8
    progression = FibonacciProgression(2, 2)

    for _ in range(n-1):
        next(progression)

    print(next(progression))
