#!/usr/bin/env python

# ch4_ex26

from sys import argv


class TowerOfHanoi:
    def __init__(self, size):
        self._size = size

    def play(self):
        self._A = []
        self._B = []
        self._C = list(range(self._size, 0, -1))
        self._print()

        self._move(self._C, self._A, self._B, self._size)

    def _print(self):
        print(self._A)
        print(self._B)
        print(self._C)
        print("--------------------------")

    def _move(self, source, target, tmp, n):
        if n > 0:
            self._move(source, tmp, target, n - 1)

            target.append(source.pop())
            self._print()

            self._move(tmp, target, source, n - 1)


if __name__ == "__main__":
    TowerOfHanoi(int(argv[1])).play()
