#!/usr/bin/env python

# ch4/ex27

import os
from sys import argv


def walk(path):
    if os.path.isdir(path):
        yield from _walk(path)


def _walk(path):
    result = (path, [], [])
    for filename in os.listdir(path):
        index = 1 if os.path.isdir(os.path.join(path, filename)) else 2
        result[index].append(filename)
    yield result
    for dir_name in result[1]:
        yield from _walk(os.path.join(path, dir_name))


if __name__ == "__main__":
    # if no arg is provided, we'll walk the path of exercises
    path = argv[1] if len(argv) > 1 else os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
    result = walk(path)
    for dir_info in result:
        print(dir_info)
