#!/usr/bin/env python

# ch6_ex20
from sys import argv

from solutions.vendor.ch06.array_stack import ArrayStack


def get_permutations(n: int):
    result = []
    stack = ArrayStack()
    for i in range(1, n + 1):
        stack.push(([i], [j for j in range(1, n + 1) if j != i]))

    while not stack.is_empty():
        current, remaining = stack.pop()
        if len(remaining) == 0:
            result.append(current)
        else:
            for i in range(len(remaining)):
                _next = current.copy()
                _next.append(remaining[i])
                stack.push((_next, remaining[:i] + remaining[i + 1:]))

    return result


def _main():
    permutations = get_permutations(int(argv[1]) if len(argv) > 1 else 3)
    for permutation in permutations:
        print(permutation)


if __name__ == "__main__":
    _main()
