#!/usr/bin/env python

# ch5_ex27
import random
from sys import argv
from math import log2, ceil


def get_int_not_in(ints):
    num_bits = ceil(log2(len(ints))) + 1
    counts = [0] * (2 ** num_bits)

    for i in ints:
        counts[i] += 1

    for i in range(len(counts)):
        if counts[i] == 0:
            return i

    return -1


def _main():
    desired_length = int(argv[1]) if len(argv) > 1 else random.randrange(1, 17)
    num_bits = ceil(log2(desired_length)) + 1
    ints = []
    seen = set(ints)
    while len(ints) < desired_length:
        r = random.randrange(2 ** num_bits)
        if r not in seen:
            ints.append(r)
            seen.add(r)
    print(ints)
    print(get_int_not_in(ints))


if __name__ == "__main__":
    _main()
