#!/usr/bin/env python3

# ch5/ex7

from solutions.libs.utils.argv import parse_int_list


def find_repeat(lst):
    n = len(lst)
    expected_sum = n * (n - 1) // 2

    actual_sum = 0
    for num in lst:
        actual_sum += num

    return actual_sum - expected_sum


if __name__ == "__main__":
    print(find_repeat(parse_int_list(1)[0]))
