#!/usr/bin/env python

# ch2_ex6_sc1

from sys import argv
from solutions.fragments.ch2.CreditCard import CreditCard as Ch2CreditCard

class CreditCard(Ch2CreditCard):
    def make_payment(self, amount):
        if amount < 0:
            raise ValueError('Amount must be nonnegative!')
        else:
            return super().make_payment(amount)

if __name__ == "__main__":
    price, amount = argv[1], argv[2]

    credit_card = CreditCard('Wilbur Smith', 'A Bank', '12345 67890', 5000.0)

    credit_card.charge(float(price))
    credit_card.make_payment(float(amount))

    print("Balance: %.2f" % credit_card.get_balance())
    print("Remaining limit: %.2f" % (credit_card.get_limit() - credit_card.get_balance()))
