#!/usr/bin/env python3

# ch6/ex27
import random

from sys import argv
from solutions.vendor.ch06.array_queue import ArrayQueue
from solutions.vendor.ch06.array_stack import ArrayStack


def scan(S: ArrayStack, x, Q: ArrayQueue = ArrayQueue()):
    result = False
    while not S.is_empty():
        curr = S.pop()
        Q.enqueue(curr)
        if curr == x:
            result = True
            break
    original_len_of_Q = len(Q)
    while not Q.is_empty():
        S.push(Q.dequeue())
    for _ in range(original_len_of_Q):
        Q.enqueue(S.pop())
    while not Q.is_empty():
        S.push(Q.dequeue())
    return result


def _print_state(S, Q):
    print("S: {}".format(S))
    print("Q: {}".format(Q))


def _main():
    n = int(argv[1]) if len(argv) > 1 else 10
    x = int(argv[2]) if len(argv) > 2 else random.randrange(n + n)
    S = ArrayStack()
    for i in range(n):
        S.push(i)
    Q = ArrayQueue()
    print("x: {}".format(x))
    _print_state(S, Q)
    print("Is {} in S? {}".format(x, scan(S, x, Q)))
    _print_state(S, Q)


if __name__ == "__main__":
    _main()
