#!/usr/bin/env python

# ch3/ex50

from sys import argv
from solutions.libs.utils.argv import parse_int_list


# We are going to model the coefficients as a list of numbers of
# length degree + 1. We start with the value of a_0 at index 0 and
# end with the value of a_d at index d.

# O(n^2)
def poly_calc_n2(x, coefficients):
    result = 0
    for i in range(len(coefficients)):
        term = 1
        for _ in range(i):
            term *= x
        term *= coefficients[i]
        result += term
    return result


if __name__ == "__main__":
    print(poly_calc_n2(int(argv[1]), parse_int_list(2)[0]))
