#!/usr/bin/env python

# ch3/ex50/2

from sys import argv
from build.lib.solutions.libs.utils.argv import parse_int_list


# We are going to model the coefficients as a list of numbers of
# length degree + 1. We start with the value of a_0 at index 0 and
# end with the value of a_d at index d.

# O(nlg(n))
def poly_calc_nlgn(x, coefficients):
    result = 0
    for i in range(len(coefficients)):
        if i == 0:
            pow_x = 1
        else:
            j = i
            pow_x = x
            while j > 1:
                pow_x *= pow_x
                j //= 2
            # oddness test
            if i > 1 and i & 1 == 1:
                pow_x *= x
        result += coefficients[i] * pow_x
    return result


if __name__ == "__main__":
    print(poly_calc_nlgn(int(argv[1]), parse_int_list(2)[0]))