#!/usr/bin/env python3

# ch6/ex18
from sys import argv

from solutions.exercises.ch6.ex3.transfer import transfer
from solutions.vendor.ch06.array_stack import ArrayStack as Ch6ArrayStack


def reverse(S: Ch6ArrayStack):
    U = Ch6ArrayStack()
    V = Ch6ArrayStack()

    transfer(S, U)
    transfer(U, V)
    transfer(V, S)


def _main():
    S = Ch6ArrayStack()
    for i in range(int(argv[1]) if len(argv) > 1 else 10):
        S.push(i)
    print("S: {}".format(S))
    print("Reversing S ...")
    reverse(S)
    print("S: {}".format(S))


if __name__ == "__main__":
    _main()
