#!/usr/bin/env python3

# ch6/ex26
from sys import argv

from solutions.exercises.ch6.ex26.stack_deque import StackDeque


def _main():
    n = int(argv[1]) if len(argv) > 1 else 10
    deque = StackDeque()
    for i in range(0, n, 2):
        if not deque.is_empty():
            print("first: {}".format(deque.first()))
            print("last: {}".format(deque.last()))
        print("deque: {}".format(deque))
        print("add_first {} onto deque ...".format(i))
        deque.add_first(i)
        print("add_last {} onto deque ...".format(i + 1))
        deque.add_last(i + 1)
    while not deque.is_empty():
        print("first: {}".format(deque.first()))
        print("last: {}".format(deque.last()))
        print("deque: {}".format(deque))
        print("delete_first {} off of queue.".format(deque.delete_first()))
        print("delete_last {} off of queue.".format(deque.delete_last()))
    print(deque)


if __name__ == "__main__":
    _main()
