#!/usr/bin/env python3

# ch5/ex35
import random
from sys import argv

from solutions.exercises.ch5.ex35.substitution_cipher import SubstitutionCipher


def _main():
    if len(argv) < 2:
        forward = [chr(i + ord('A')) for i in range(26)]
        random.shuffle(forward)
        forward = ''.join(forward)
    else:
        forward = argv[1]
    original_msg = "HELLO WORLD!" if len(argv) < 3 else argv[2]

    cc = SubstitutionCipher(forward)
    print("Original Message: {}".format(original_msg))
    encrypted_msg = cc.encrypt(original_msg)
    print("Encrypted Message: {}".format(encrypted_msg))
    print("Decrypted Message: {}".format(cc.decrypt(encrypted_msg)))


if __name__ == "__main__":
    _main()
