#!/usr/bin/env python

# ch2_ex31_sc1

from sys import argv
from solutions.fragments.ch2.Progression import Progression as Ch2Progression


class DifferenceProgression(Ch2Progression):
    def __init__(self, start=2, nnext=200):
        self._next = nnext
        super().__init__(start)

    def _advance(self):
        tmp = self._current
        self._current = self._next
        self._next = abs(tmp - self._next)


if __name__ == "__main__":
    if len(argv) > 2:
        progression = DifferenceProgression(int(argv[1]), int(argv[2]))
    else:
        progression = DifferenceProgression()

    n = int(argv[3]) if len(argv) > 3 else 20
    progression.print_progression(n)
