#!/usr/bin/env python3

# ch1_ex7_sc1

import sys

def sum_of_odd_squares(limit):
    assert isinstance(limit, int) and limit > 0
    return sum (i*i for i in range(1, limit) if i & 1 == 1)

if __name__ == "__main__":
    limit = int(sys.argv[1])
    print("Sum of the squares of all odd positive integers less than %i: %i" %(limit, sum_of_odd_squares(limit)))