#!/usr/bin/env python

# ch6/ex19
from sys import argv

from solutions.vendor.ch06.array_stack import ArrayStack


def is_matched_html(raw: str):
    """Return True if all HTML tags are properly match; False otherwise."""
    S = ArrayStack()
    j = raw.find('<')  # find first '<' character (if any)
    while j != -1:
        k = raw.find('>', j + 1)  # find next '>' character
        if k == -1:
            return False  # invalid tag
        tag = raw[j + 1:k].lstrip().split()[0]  # strip away < >, leading whitespace, and all attributes
        if not tag.startswith('/'):  # this is opening tag
            S.push(tag)
        else:  # this is closing tag
            if S.is_empty():
                return False  # nothing to match with
            if tag[1:] != S.pop():
                return False  # mismatched delimiter
        j = raw.find('<', k + 1)  # find next '<' character (if any)
    return S.is_empty()  # were all opening tags matched?


def _main():
    print(is_matched_html(argv[1]))


if __name__ == "__main__":
    _main()
