#!/usr/bin/env python

# ch4_ex10

from sys import argv


def lg_floor(n):
    if n == 1:
        return 0
    else:
        return 1 + lg_floor(n // 2)


if __name__ == "__main__":
    print(lg_floor(int(argv[1])))
