#!/usr/bin/env python

# ch6/ex21

from solutions.libs.utils.argv import parse_int_list
from solutions.vendor.ch06.array_queue import ArrayQueue
from solutions.vendor.ch06.array_stack import ArrayStack


def get_every_subset(_set):
    stack = ArrayStack()
    result = ArrayQueue()

    for ele in _set:
        stack.push(ele)
    result.enqueue({})

    while not stack.is_empty():
        curr_ele = stack.pop()
        curr_len = len(result)
        for _ in range(curr_len):
            old_subset = result.dequeue()
            new_subset = set(old_subset)
            new_subset.add(curr_ele)
            result.enqueue(old_subset)
            result.enqueue(new_subset)

    return result


def _main():
    result = get_every_subset(set(parse_int_list(1)[0]))  # remove any duplicates in list
    while not result.is_empty():
        print(result.dequeue())


if __name__ == "__main__":
    _main()
