#!/usr/bin/env python

# ch2/ex14

from solutions.vendor.ch02.vector import Vector as Ch2Vector
from solutions.libs.utils.argv import parse_int_list


class Vector(Ch2Vector):
    def __mul__(self, other):
        """Return dot product result."""
        if isinstance(other, Ch2Vector):
            if len(self) != len(other):
                raise ValueError('dimensions must agree')
            return sum(self[i] * other[i] for i in range(len(self)))
        else:
            return NotImplemented


if __name__ == "__main__":
    current_index = 1
    seq_v, current_index = parse_int_list(current_index)
    seq_u = parse_int_list(current_index)[0]

    vector_v = Vector(len(seq_v))
    for i in range(len(vector_v)):
        vector_v[i] = seq_v[i]

    vector_u = Vector(len(seq_u))
    for i in range(len(vector_u)):
        vector_u[i] = seq_u[i]

    print(vector_v * vector_u)
