#!/usr/bin/env python

# ch1_ex27_2

from sys import argv


def increasing_factors(n):
    k = 1
    while k * k < n:
        if n % k == 0:
            yield k
        k += 1
    if k * k == n:
        yield k
    k -= 1
    while k > 0:
        if n % k == 0:
            yield n // k
        k -= 1


if __name__ == "__main__":
    n = int(argv[1])
    print("The factors of %i in increasing order are: %s" % (n, list(increasing_factors(n))))
