#!/usr/bin/env python

# ch1_ex27

from sys import argv


def increasing_factors(n):
    k = 1
    buffer = []
    while k * k < n:
        if n % k == 0:
            yield k
            buffer.append(n // k)
        k += 1
    if k * k == n:
        yield k
    last_buffer_index = len(buffer) - 1
    for i in range(len(buffer)):
        yield buffer[last_buffer_index - i]


if __name__ == "__main__":
    n = int(argv[1])
    print("The factors of %i in increasing order are: %s" % (n, list(increasing_factors(n))))
