#!/usr/bin/env python

# ch5_ex25
from sys import argv
import random

from solutions.vendor.ch05.dynamic_array import DynamicArray as Ch5DynamicArray


class DynamicArray(Ch5DynamicArray):

    def remove_all(self, value):
        count = 0
        for i in range(self._n):
            if self._A[i] == value:
                count += 1
                self._A[i] = None
            else:
                self._A[i - count] = self._A[i]
                if i > self._n - count - 1:
                    self._A[i] = None
        self._n -= count
        if self._n < self._capacity // 4:
            self._resize(self._capacity // 2)

    def __str__(self):
        s = ["[ "]
        for i in range(self._n):
            s.append(str(self._A[i]))
            s.append(' ')
        s.append("]")
        return ''.join(s)


def _main():
    a = DynamicArray()
    for i in range(int(argv[1]) if len(argv) > 1 else 20):
        a.append(i)
        if random.random() > 0.5:
            a.append(20)
    print(a)
    print("remove_all(20)")
    a.remove_all(20)
    print(a)


if __name__ == "__main__":
    _main()
