#!/usr/bin/env python

# ch1_ex23

from random import randrange
from solutions.libs.utils.argv import parse_int_list

if __name__ == "__main__":
    seq = parse_int_list(1)[0]
    try:
        print(seq[randrange(0, len(seq) * 2)])
    except IndexError:
        print("Don’t try buffer overflow attacks in Python!")