#!/usr/bin/env python3

# ch1_ex13_sc2

from solutions.libs.utils.argv import parse_int_list

def destructive_reverse(seq):
    last_index = len(seq) - 1
    for i in range(0, len(seq) // 2):
        temp = seq[i]
        seq[i] = seq[last_index - i]
        seq[last_index - i] = temp
    return seq

if __name__ == "__main__":
    print(destructive_reverse(parse_int_list(1)[0]))