#!/usr/bin/env python3

# ch1_ex13_sc1

from solutions.libs.utils.argv import parse_int_seq

def non_destructive_reverse(seq):
    result = []
    for i in range(len(seq) - 1, -1, -1):
        result.append(seq[i])
    return result

if __name__ == "__main__":
    print(non_destructive_reverse(parse_int_seq(1)[0]))