#!/usr/bin/env python3

# ch1_ex3_sc1

from solutions.libs.utils.argv import parse_int_seq

def minmax(seq):
    min = seq[0]
    max = seq[0]

    for i in seq:
        if i < min:
            min = i
        elif i > max:
            max = i
    return min, max

if __name__ == "__main__":
    seq = parse_int_seq(1)[0]
    min, max = minmax(seq)
    print("min: %i\nmax: %i" %(min, max))
