#!/usr/bin/env python3

# ch1_ex20_sc1

from random import randint
from solutions.libs.utils.argv import parse_int_list
from solutions.libs.decorators.dynamic.ListDecorator import ListDecorator


def shuffle(lst):
    lst_dec = ListDecorator(lst)
    last_index = len(lst_dec) - 1
    for i in range(0, last_index):
        lst_dec.swap(i, randint(i, last_index))
    return lst


if __name__ == "__main__":
    print(shuffle(parse_int_list(1)[0]))
