#!/usr/bin/env python3

# ch1_ex20_sc1

from random import randint
from solutions.libs.utils.argv import parse_int_list

def shuffle(seq):
    last_index = len(seq) - 1
    for i in range(0, last_index):
        tmp = seq[i]
        rnd = randint(i, last_index)
        seq[i] = seq[rnd]
        seq[rnd] = tmp
    return seq


if __name__ == "__main__":
    print(shuffle(parse_int_list(1)[0]))