#!/usr/bin/env python3

# ch1_ex24_sc1

def vowel_count(string):
    vowels = "aeiou"
    count = 0
    for char in string:
        if char in vowels:
            count += 1
    return count

if __name__ == "__main__":
    print("Number of vowels: %i" %(vowel_count(input("Please enter a string: "))))
