#!/usr/bin/env python

# ch6/ex24
from sys import argv

from solutions.exercises.ch6.ex24.queue_stack import QueueStack


def _main():
    n = int(argv[1]) if len(argv) > 1 else 10
    stack = QueueStack()
    for i in range(n):
        if not stack.is_empty():
            print("top: {}".format(stack.top()))
        print("stack: {}".format(stack))
        print("Pushing {} onto stack ...".format(i))
        stack.push(i)
    while not stack.is_empty():
        print("top: {}".format(stack.top()))
        print("stack: {}".format(stack))
        print("Popped {} off of stack.".format(stack.pop()))




if __name__ == "__main__":
    _main()