#!/usr/bin/env python

# ch1_ex17

import sys
from solutions.libs.utils.argv import parse_int_list


def scale(data, factor):
    for val in data:
        val *= factor
    return data


if __name__ == "__main__":
    current_index = 1
    data, current_index = parse_int_list(current_index)
    factor = int(sys.argv[current_index])
    print(scale(data, factor))
