#!/usr/bin/env python3

# ch1/ex15

from solutions.libs.utils.argv import parse_int_list


def is_distinct(seq):
    observed_values = {}

    for n in seq:
        value_str = str(n)
        if value_str in observed_values:
            return False
        observed_values[value_str] = value_str
    return True


if __name__ == "__main__":
    seq = parse_int_list(1)[0]
    print("%s has %s values." % (seq, "only distinct" if is_distinct(seq) else "duplicate"))
