#!/usr/bin/env python

# ch2_ex12

from numbers import Real
from sys import argv
from solutions.vendor.ch02.vector import Vector as Ch2Vector
from solutions.libs.utils.argv import parse_int_list


class Vector(Ch2Vector):
    def __mul__(self, scalar):
        """Return scalar multiplication result."""
        if isinstance(scalar, Real):
            result = Vector(len(self))
            for i in range(len(self)):
                result[i] = self[i] * scalar
            return result
        else:
            return NotImplemented


if __name__ == "__main__":
    seq_v, current_index = parse_int_list(1)
    if argv[1].lstrip('-+').isdigit():
        scalar = int(argv[current_index])
    else:
        scalar = float(argv[current_index])

    vector_v = Vector(len(seq_v))
    for i in range(len(vector_v)):
        vector_v[i] = seq_v[i]

    print(vector_v * scalar)
