#!/usr/bin/env python3

# ch1/ex25

def strip_punct(string):
    punctuation = "[!\"#$%&'()*+,./:;<=>?@\^_`{|}~-]"
    result = []
    for char in string:
        if char not in punctuation:
            result.append(char)
    return "".join(result)


if __name__ == "__main__":
    print(strip_punct(input("Please enter a string: ")))
