#!/usr/bin/env python3

# ch1/ex25/2

import re


def strip_punct_with_regex(string):
    return re.sub(r"[\[\]!\"#$%&'()*+,./:;<=>?@\\^_`{|}~\-]", "", string)


if __name__ == "__main__":
    print(strip_punct_with_regex(input("Please enter a string: ")))
