#!/usr/bin/env python3

# ch1_ex17_sc1

import sys
from solutions.libs.utils.argv import parse_int_seq

def scale(data, factor):
    for val in data:
        val *= factor
    return data

if __name__ == "__main__":
    current_index = 1
    data, current_index = parse_int_seq(current_index)
    factor = int(sys.argv[current_index])
    print(scale(data, factor))