#!/usr/bin/env python

# ch1/ex13/2

from solutions.libs.utils.argv import parse_int_list
from solutions.libs.decorators.dynamic.ListDecorator import ListDecorator


def destructive_reverse(lst):
    lst_dec = ListDecorator(lst)
    last_index = len(lst_dec) - 1
    for i in range(0, len(lst_dec) // 2):
        lst_dec.swap(i, last_index - i)
    return lst


if __name__ == "__main__":
    print(destructive_reverse(parse_int_list(1)[0]))
