#!/usr/bin/env python

# ch1/ex13

from solutions.libs.utils.argv import parse_int_list


def non_destructive_reverse(seq):
    result = []
    for i in range(len(seq) - 1, -1, -1):
        result.append(seq[i])
    return result


if __name__ == "__main__":
    print(non_destructive_reverse(parse_int_list(1)[0]))
