#!/usr/bin/env python

# ch6/ex25
from sys import argv

from solutions.exercises.ch6.ex25.stack_queue import StackQueue


def _main():
    n = int(argv[1]) if len(argv) > 1 else 10
    queue = StackQueue()
    for i in range(n):
        if not queue.is_empty():
            print("first: {}".format(queue.first()))
        print("queue: {}".format(queue))
        print("Enqueued {} onto queue ...".format(i))
        queue.enqueue(i)
    while not queue.is_empty():
        print("first: {}".format(queue.first()))
        print("queue: {}".format(queue))
        print("Dequeued {} off of queue.".format(queue.dequeue()))
    print(queue)


if __name__ == "__main__":
    _main()
