#!/usr/bin/env python

# ch2/ex10

from solutions.vendor.ch02.vector import Vector as Ch2Vector
from solutions.libs.utils.argv import parse_int_list


class Vector(Ch2Vector):
    def __neg__(self):
        result = Vector(len(self))
        for i in range(len(self)):
            result[i] = - self[i]
        return result


if __name__ == "__main__":
    seq_a = parse_int_list(1)[0]

    vector_a = Vector(len(seq_a))
    for i in range(len(vector_a)):
        vector_a[i] = seq_a[i]

    print(-vector_a)
