#!/usr/bin/env python3

# ch2/ex37

from sys import argv

from solutions.exercises.ch2.ex37.game_master import GameMaster


def _main():
    size = argv[1] if len(argv) > 1 else 40
    fish = argv[2] if len(argv) > 2 else 15
    bears = argv[3] if len(argv) > 3 else 5
    GameMaster(size, fish, bears).officiate_game()


if __name__ == "__main__":
    _main()
