#!/usr/bin/env python

# ch2/ex22

from solutions.libs.utils.argv import parse_list
from solutions.vendor.ch02.sequence_abc import Sequence as Ch2Sequence


class Sequence(Ch2Sequence):

    def __init__(self, seq):
        self._seq = seq

    def __len__(self):
        return len(self._seq)

    def __getitem__(self, index):
        return self._seq[index]

    def __eq__(self, other):
        if len(self) != len(other):
            return False
        for i in range(len(self)):
            if self[i] != other[i]:
                return False
        return True


if __name__ == "__main__":
    current_index = 1
    list_a, current_index = parse_list(current_index)
    list_b = parse_list(current_index)[0]

    print(Sequence(list_a) == Sequence(list_b))
