#!/usr/bin/env python

# ch6/ex5
from sys import argv

from solutions.vendor.ch06.array_stack import ArrayStack as Ch6ArrayStack


def reverse(lst: list):
    s = Ch6ArrayStack()
    for ele in lst:
        s.push(ele)
    for i in range(len(lst)):
        lst[i] = s.pop()


def _main():
    lst = [i for i in range(int(argv[1]) if len(argv) > 1 else 10)]
    print("lst: {}".format(lst))
    print("Reversing lst ...")
    reverse(lst)
    print("lst: {}".format(lst))


if __name__ == "__main__":
    _main()
