#!/usr/bin/env python

# ch2/ex27

from sys import argv
from solutions.vendor.ch02.range import Range as Ch2Range


class Range(Ch2Range):
    def __contains__(self, item):
        return (self._start <= item
                and (item - self._start) % self._step == 0
                and (item - self._start) // self._step < len(self))


if __name__ == "__main__":
    item, stop = int(argv[1]), int(argv[2])
    print("%i is %sin Range(%i)" % (item, "" if item in Range(stop) else "not ", stop))
