#!/usr/bin/env python3

# ch4/ex7

from sys import argv


def str_to_int(s):
    return _str_to_int(s, len(s))


def _str_to_int(s, n):
    if n == 0:
        return None
    else:
        curr = ord(s[n - 1]) - ord("0")
        if n == 1:
            return curr
        else:
            return curr + 10 * _str_to_int(s, n - 1)


if __name__ == "__main__":
    print(str_to_int(argv[1]))
